---
- name: iTermの設定
  ansible.builtin.file:
    src: "{{ role_path }}/files/com.googlecode.iterm2.plist"
    dest: "{{ ansible_env.HOME }}/Library/Preferences/com.googlecode.iterm2.plist"
    state: link
    force: yes
