- name: デフォルトshellをHomebrewで入れたzshに変更
  become: true
  ansible.builtin.user:
    name: tanavel
    shell: /usr/local/bin/zsh

- name: zshrcのシンボリックリンクを張る
  ansible.builtin.file:
    src: "{{ role_path }}/files/zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
