---
- name: Homebrew本体とインストール済みパッケージの更新
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: tapを追加
  community.general.homebrew_tap:
    name: "{{ taps }}"

- name: CLIアプリケーション
  community.general.homebrew:
    name: "{{ item }}"
  loop: "{{ fomulae }}"

- name: GUIアプリケーション
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ casks }}"

- name: フォント
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ fonts }}"
