---
- name: Update Homebrew and packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Install hashicorp tap
  community.general.homebrew_tap:
    name: hashicorp/tap

- name: Install fomulae
  community.general.homebrew:
    name: "{{ item }}"
  loop: "{{ fomulae }}"

- name: Install homebrew font manager
  community.general.homebrew_tap:
    name: homebrew/cask-fonts

- name: Install fonts
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ fonts }}"

- name: Install casks
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ casks }}"
